plugins {
    id 'java'
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(21))
  }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly 'net.portswigger.burp.extender:burp-extender-api:2.3'
    implementation 'com.drewnoakes:metadata-extractor:2.21.0'
}

sourceSets {
    main {
        java {
            srcDir 'src'
        }
    }
}

task fatJar(type: Jar) {
    //baseName = project.name + '-all'
    //baseName = 'ils-all'
    //from { configurations.implementation.collect { it.isDirectory() ? it : zipTree(it) } }
    //with jar
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
