plugins {
    id 'java'
}

/* This setting depends on your Java installation:
   - veggiespam needs version 23.
   - portswigger needs version 21.
   - wolf needs version 22. */
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(23))
  }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly 'net.portswigger.burp.extender:burp-extender-api:2.3'
    compileOnly 'net.portswigger.burp.extensions:montoya-api:2026.2'
    implementation 'com.drewnoakes:metadata-extractor:2.21.0'
}

sourceSets {
    main {
        java {
            srcDir 'src'
        }
    }
}

task fatJar(type: Jar) {
    //baseName = project.name + '-all'
    //baseName = 'ils-all'
    //from { configurations.implementation.collect { it.isDirectory() ? it : zipTree(it) } }
    //with jar
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
